### PR TITLE
Added grammar for boolean operators parser.

### PR DESCRIPTION
**Pull request by momosahi**
Hey.
I added the grammer for boolean opeator parser in CalculatorExpression.g4. 
I let you check because I am not absolutely sure of what I did.

### CODE REVIEW

**Comment by AlixDeclerck** [comment]
Okay, very nice :+1: 
Just seen that src/main/resources/CalculatorExpression.g4 was in conflict. The pow rule and the number +boolean rule didn't merge on git hub. So I just push a conflict resolution. Application and tests are both working but pow seam unused parser rule, I don't know if it's expected result or if you wanna just delete it. So feel free to do what's need to be done :-)

**Comment by AlixDeclerck** [comment]
After resolving the conflicts on this I'm probably no more a person who should do this review / merging pull request .. So .. Next :-)

**Comment by lavendthomas** [comment]
Hello,

@momosahi, I finally managed to find the time to implement the parser for booleans, **but my code is untested**.  Can you please test that everything works as you wanted it to work.

Also, parsing booleans inside of functions might not work properly. Is that a desired feature?

And finally, I find it quite strange that we can manipulate booleans but we don't support comparison operators such as `<` or `>=`. Supporting requests like `1 < 2` would make a lot of sense in the context of booleans. It is something you plan to implement?

Have a nice day,
Thomas

**Comment by lavendthomas** [comment]
@momosahi are you planning to add support for comparisons, or can I merge this PR?

**Comment by momosahi** [comment]
Hello Thomas,

I had not planned to add support for comparison operation such as 1 > 2 because I thought it was the same as putting true or false directly.

**Comment by lavendthomas** [comment]
Hello @momosahi,

I'll merge the code as it doesn't cause any harm to the software. However, the GUI is not yet adapted to use booleans. So, in theory it could work but there is not way to handle booleans in the GUI. @laurencefloriani proposed to help you a few weeks ago by creating a boolean section to the app, but I think she doesn't have the time anymore. I still think that creating a new section in the GUI is the way to go.

**Pull request merged**
