### PR TITLE
10 feature supporting boolean logic

### PR DESCRIPTION
**Pull request by momosahi**

### CODE REVIEW

**Comment by lavendthomas** [comment]
Hello, and thank you! Could you please make sure that the tests are running properly. I personally can't compile the code because of some missing imports and for example, you changed Visitor.java (a bad merge?) and in Calculator.java, you call Evaluator.getBoolResult(), which doesn't exist.

I tried to make some changes to help, but I couldn't fix trivially all issues.

**Comment by momosahi** [comment]
Hello Thomas,

Thanks for the message and for trying to solve the problem.

I think the errors are due to a bad merge, I probably made a bad merge
while trying to solve the conflicts (it was my first time).
I will make sure that everything works fine and make another pull request.

Have a nice day

Le dim. 17 avr. 2022 à 08:46, lavendthomas ***@***.***> a
écrit :

**Comment by lavendthomas** [comment]
Hello Sahi,

No worries about the bad merge, we're all here to learn :wink: 

The code now looks fine by me. I just fear that one of the `return null` for unsupported operations will come back to bite us later.
Also, boolean operations need to be added to the CalculatorExpression.g4 file to parse them correctly. Do you want to do it, or do you want me to do it? You'll need the ANTLR4 plugin in IntelliJ to re-generate the files in the `parser` package. I'll create a new issue for it, so that we can merge this issue.

**Comment by momosahi** [comment]
Hello Thomas,

Okay. I will do it (add boolean operations in CalculatorExpression.g4).

Thanks.

Le dim. 17 avr. 2022 à 17:14, lavendthomas ***@***.***> a
écrit :

**Pull request merged**
